#!/bin/bash
apt update 
read -p "请输入网站的根目录，默认/mnt/sda1/nginx:" www_dir

if [ $www_dir == "" ];then
www_dir="/mnt/sda1/nginx"
fi

if [ -e /usr/bin/ffmpeg ];then
echo "已经安装了ffmpeg"

else 
apt install ffmpeg -y
fi
if [ -e /usr/bin/rename ];then

echo "已经安装了rename"
else

apt install rename -y
fi

echo "正在去除文件名的空格"

rename 's/[[:space:]]//g' *

echo "正在去除文件名的特殊符号"
rename 's/\&//g' *
rename 's/\#//g' *

dir_name_check=`pwd`
title=${dir_name_check##*/}


echo "检测到你的本级目录是$title"


rm -rf *.gif


rm -rf *.jpeg

    function read_dir(){
        for file in `ls $1`       #注意此处这是两个反引号，表示运行系统命令
        do
		formats=$(echo $file |cut -d '.' -f 2)

            if [ -d $file ]  #注意此处之间一定要加上空格，否则会报错
            then

		    echo "目录掠过"


	    elif [ $formats != "mp4" ]
	    then

		     rename_name=$(echo $file |cut -d '.' -f 1)

mv ./$file  $rename_name.mp4 



            else
 img_name=$(echo $file |cut -d '.' -f 1)

#ffmpeg -i ./$file -ss 60 -vframes 1 $img_name.jpg
#ffmpeg -ss $time -t 10 -i  ./$file  -s 800x600 -f gif -r 1 $img_name.gif
#老的命令因为生成的gif不好看

hour=`ffmpeg -i ./$file  2>&1 | grep Du | awk '{print "\t" $2 }' | cut -d ':' -f 1| sed 's/[[:space:]]//g'`
echo "这个视频是$hour小时"
minutes=`ffmpeg -i ./$file  2>&1 | grep Du | awk '{print "\t" $2 }' | cut -d ':' -f 2`
echo "这个视频是$minutes分钟"
seconds=`ffmpeg -i ./$file  2>&1 | grep Du | awk '{print "\t" $2 }' | cut -d ':' -f 3| cut -d '.' -f 1 `
echo "这个视频是$seconds秒"

chose_hour=`printf "%02d" $(($hour / 2 ))`
chose_minutes=`printf "%02d" $(($minutes / 2))`

chose_seconds=`printf "%02d" $(($seconds / 2))`
echo "$chose_hour:$chose_minutes:$chose_seconds"




ffmpeg -ss  $chose_hour:$chose_minutes:$chose_seconds -t 10 -i ./$file -r 1 -s  800x600 -f image2 $img_name-%03d.jpeg
ffmpeg -f image2 -framerate 5 -i ./$img_name-%03d.jpeg $img_name.gif




            fi
        done
    }       #读取第一个参数

read_dir $1
if [ -d $www_dir/photo/porn_cate/$title ];then
	echo "已经存在"
	rm -rf $www_dir/photo/porn_cate/$title/*
else

mkdir $www_dir/photo/porn_cate/$title
fi
rm *.jpeg
mv ./*.gif  $www_dir/photo/porn_cate/$title
cat $www_dir/p.php  > $www_dir/$title.php

dir_name_check=`pwd`
title=${dir_name_check##*/}

sed  "52c fileShow(\'./photo/porn_cate/$title\',\'$dir_name_check\');"   -i  $www_dir/$title.php
sed  's/\/mnt\/sda1\/nginx/./g' -i /mnt/sda1/nginx/$title.php
sed "21c <p>$title</p>"  -i /mnt/sda1/nginx/$title.php



